## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [2]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [35]:
A = np.array([0.6, -15, 2, 5, 98])[np.newaxis]
A = A.T
B= np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])
print(A.shape)
print(B.shape)
C =A*B
print(C)
print(C[1,2]) # C23 when C = B*A or C =A*B

(5, 1)
(5, 3)
[[   1.2    1.2   -2.4]
 [-135.   210.    -0. ]
 [  26.    -1.    88. ]
 [   5.    45.    20. ]
 [   0.     0.   490. ]]
-0.0


In [9]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    A = [A[i]+[int(i==j) for j in range(len(A))] for i in range(len(A))]    # Stacking identity matrix
    for i in range(len(A)): 
        A[i:] = sorted(A[i:], key=lambda r: -abs(r[i]))
        A[i] = [A[i][j]/A[i][i] for j in range(len(A)*2)]
        A = [[A[j][k] if i==j else A[j][k]-A[i][k]*A[j][i] for k in range(len(A)*2)] for j in range(len(A))]
    
    return [A[i][-len(A):] for i in range(len(A))]


In [10]:
n = [[1,2,3], [0,1,4], [5,6,0]]
inverse_matrix(n)

[[-23.99999999999998, 17.999999999999986, 4.9999999999999964],
 [19.999999999999982, -14.999999999999988, -3.999999999999997],
 [-4.999999999999996, 3.999999999999997, 0.9999999999999992]]

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [34]:
# Just answer using code --> easy stuff!
A = np.array([[3, 0.6, 4, -3], [-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3,-5.76,45,0],[2,-2,1.3,9],[-9,0,0,0]])
C = np.array([[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]])
D = A+B-C

def give_element(matrix,i,j):
    return matrix[i,j]
print(D)
print(give_element(D,1,2))  # for i=2 and j=3
print(give_element(D,2,0))  # for i=3 and j =1
# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]
-2.7
5.7


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [32]:
A = np.array([0.6, -15, 2, 5, 98])[np.newaxis]
A = A.T
B= np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])
print(A.shape)
print(B.shape)
C =A*B
def rows_colums_value(matrix,i,j):
    rows = matrix.shape[0]
    columns = matrix.shape[1]
    value = matrix[i,j]
    return rows,columns,value

rws, clms, value = rows_colums_value(C,0,2)
print("Matrix have a " + str(rws) +' rows, and '+ str(clms) +' columns.')
print("C13 = ",value)

(5, 1)
(5, 3)
Matrix have a 5 rows, and 3 columns.
C13 =  -2.4
